stages:
  - test

deploy_vps:
  stage: test
  tags:
    - BSFFR
  script:
    - echo SALAM
    - echo $USER
    - echo $SHELL
    - echo $PATH
# build_job:
#   stage: build
#   tags:
#     - BSFFR
#   script:
#     - docker build -t $TAG_COMMIT -t $TAG_LATEST .
#     # - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#     # - docker push $TAG_COMMIT
#     # - docker push $TAG_LATEST

# deploy_job:
#   image: alpine:latest
#   stage: deploy
#   tags:
#     - deployment
#   script:
#     - chmod og= $ID_RSA
#     - apk update && apk add openssh-client
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f my-app || true"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 80:80 --name my-app $TAG_COMMIT"
#   environment:
#     name: production
#     url: http://your_server_IP
#   only:
#     - master
